import os
import asyncio
import json
from dotenv import load_dotenv
from servicenow_tools import (
    ServiceNowClient, 
    get_single_servicenow_record, 
    query_servicenow_records, 
    update_servicenow_record, 
    create_servicenow_record
)

# Load environment variables
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

async def run_tests():
    # 1. Initialize Client
    print("\n--- INITIALIZING CLIENT ---")
    client = ServiceNowClient(
        instance=os.getenv("SN_INSTANCE"),
        username=os.getenv("SN_USERNAME"),
        password=os.getenv("SN_PASSWORD")
    )
    
    try:
        # TEST 1: Get Single Record (Checking if we can read an incident)
        print("\n--- TEST 1: GET SINGLE RECORD ---")
        # Using INC0000031 from your demo data
        res_json = await get_single_servicenow_record(client, "incident", "INC0000031")
        
        if res_json.get("success") and res_json.get("count", 0) > 0:
            incident = res_json["data"][0]
            inc_sys_id = incident["sys_id"]["value"] # Extracting the 32-char sys_id
            print(f"✅ Success! Found {incident['number']['display_value']}")
            print(f"   Sys ID: {inc_sys_id}")
            print(f"   Short Description: {incident['short_description']['display_value']}")
        else:
            print("❌ Failed to fetch INC0000031. Check your credentials or ticket number.")
            return

        # TEST 2: Query Records (Checking if we can pull a list with a filter)
        print("\n--- TEST 2: QUERY RECORDS ---")
        # Querying for active incidents
        query_str = "active=true"
        q_json = await query_servicenow_records(client, "incident", query=query_str, limit=3)

        if q_json.get("success"):
            print(f"✅ Success! Found {q_json['count']} active incidents.")
        else:
            print("❌ Failed to query active records.")

        # TEST 3: Update Record (Checking if we can add a work note)
        print("\n--- TEST 3: UPDATE RECORD ---")
        # We will add a test work note to INC0000031 using the sys_id we grabbed in Test 1
        update_payload = {
            "work_notes": "Automated AI Agent Test: Verifying API update permissions."
        }
        u_json = await update_servicenow_record(client, "incident", inc_sys_id, update_payload)

        if u_json.get("success"):
            print("✅ Success! Added a work note to the incident.")
        else:
            print(f"❌ Failed to update record: {u_json.get('error')}")

        # TEST 4: Create Record (Checking if we can create a Problem ticket for Phase 4)
        print("\n--- TEST 4: CREATE RECORD ---")
        problem_payload = {
            "short_description": "AI Agent Test Problem",
            "description": "This is a test problem generated by the AI architecture validation script."
        }
        c_json = await create_servicenow_record(client, "problem", problem_payload)

        if c_json.get("success"):
            new_prb_number = c_json["data"]["number"]
            print(f"✅ Success! Created new Problem record: {new_prb_number}")
        else:
            print(f"❌ Failed to create problem record: {c_json.get('error')}")

    finally:
        # 5. Clean up connection
        await client.close()
        print("\n--- TESTS COMPLETE ---")

if __name__ == "__main__":
    asyncio.run(run_tests())